# Generated by Django 4.0.5 on 2022-07-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nltk_identify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nltk',
            name='corpus_type',
            field=models.CharField(choices=[('multiplication', 'multiplication'), ('division', 'division'), ('addition', 'addition'), ('subtraction', 'subtraction'), ('equality', 'equality'), ('stop_words', 'stop_words')], default='stop_words', max_length=25),
        ),
    ]
